export { Square } from './Square'
export { Rectangle } from './Rectangle'
export { Triangle } from './Triangle'
export { Diamond } from './Diamond'
export { Parallelogram } from './Parallelogram'
export { Trapeze } from './Trapeze'
export { Polygon } from './Polygon'
export { Circle } from './Circle'
