export { Pyramid } from './Pyramid'
export { Cube } from './Cube'
export { Parallelepiped } from './Parallelepiped'
export { Sphere } from './Sphere'
export { Cylinder } from './Cylinder'
export { Cone } from './Cone'
