export type IconsNames =
  | 'arrow back'
  | 'circle'
  | 'close'
  | 'cone'
  | 'cube'
  | 'cylinder'
  | 'dark mode'
  | 'diamond'
  | 'flat figure'
  | 'light mode'
  | 'more vert'
  | 'parallelogram'
  | 'polygon'
  | 'rectangle'
  | 'solid figure'
  | 'sphere'
  | 'square'
  | 'trapeze'
  | 'triangle'

export type ThemeContextType = [string, () => void]
